### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by Elvis10ten** [Flutterwave/rave-android#28]
The ReadMe says the READ_PHONE_STATE permission is required to get the build number for fraud detection and flagging.

It seems really weird when the user is about to pay and a permission pops up with "Allow appX to make and manage phone calls"? Sometimes it's hard coming up with a rationale to explain this.

Considering that I could use a WebView with a rave payment page (maybe even the APIs?)... Or that Paystack or some other payment SDK don't require this. Just curious if this is really needed

**Comment by biodunalfet** [comment]
Hi @Elvis10ten. Here's the justification for it https://developer.android.com/training/articles/user-data-ids.html#i_abuse_detection_detecting_high_value_stolen_credentials. 

```
With stolen credentials, devices can be used to monetize multiple high value stolen credentials (such as tokenized credit cards). In these scenarios, software IDs can be reset to avoid detection, so hardware identifiers may be used.
```

**Comment by saintjab** [comment]
I know this is closed but another question is, is this really required? Maybe the feature can be implemented without that permission now that Google is cracking down on Privacy and Security permissions. I am having hard time explaining to Google App review team why that permission which contains READ_SMS and CALL is required. I hope an alternative implementation can be made without that particular permission.

**Comment by biodunalfet** [comment]
Hi @saintjab, the `READ_PHONE_STATE` permission is totally different from the `READ_SMS` permission. The reason we use this permission is because we use `mTelephonyManager.getDeviceId()` to get a reliable id for the user's device as recommended in the [docs](https://developer.android.com/training/articles/user-data-ids.html#i_abuse_detection_detecting_high_value_stolen_credentials). I should also mention that this is not uncommon in payment apps and sdk . A typical example is the Square POS app which uses this permission [here](https://i.imgur.com/BWAfoB5.jpg). The [PayPal SDK](https://developer.paypal.com/docs/instore/wlw/android-sdk-reference/dev-environment-setup/#sample-android-manifest) also uses this
