### ISSUE TITLE
Error Retrieving transaction fees 

### ISSUE THREAD

**Issue by johnebere58** [Flutterwave/rave-android#41]
I am new to rave so when testing the code on github, i got an error message 

"Error retrieving transaction fees"

What could be the issue?

**Comment by biodunalfet** [comment]
Hi @johnebere58. You're getting this issue because you're using the wrong keys. Please check that if you're on the live environment, you set `onStagingEnv(false)` and that you're using the live keys and if you're on the staging environment, you set `onStagingEnv(true)` and that you're using the staging keys.

**Comment by devendroid** [comment]
I'm also getting same message (An error occurred while retrieving transaction fee) on pay and logcat showing this:
{"status":"error","message":"Only test cards allowed","data":{"code":"CARD_ERR","message":"Only test cards allowed"}}
I using SDK ver 1.0.38,
Setting onStagingEnv(true) and
Using test keys.

What i missing..?
